### ISSUE TITLE
Upvote & Downvote functionality

### ISSUE THREAD

**Issue by emrehayirci** [emrehayirci/deps#4]
This is a two step move:

1. Make endpoints for upvate and downvote'ing and taking it back
2. Connect it with jquery

**Comment by savasturk** [comment]
I am currently doing research on this issue and moving on.

**Comment by savasturk** [comment]
Nowadays, I haven't got enough information for html, css and javascript.So I'm having touble. This doesn't  mean I will not to do it. I just wanted to inform you.:))
